using System.Text;
using n2jSoft.ModularGuard.CLI.Models;

namespace n2jSoft.ModularGuard.CLI.Reporting;

public sealed class OptimizationMarkdownReportExporter
{
    public string Export(IReadOnlyList<OptimizationResult> results)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Project Reference Optimization Report");
        sb.AppendLine();
        sb.AppendLine($"**Generated:** {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();

        // Summary
        var totalUnused = results.Sum(r =>
            r.UnnecessaryReferences.Count(u => u.Reason == UnnecessaryReferenceReason.Unused));
        var totalTransitive = results.Sum(r =>
            r.UnnecessaryReferences.Count(u => u.Reason == UnnecessaryReferenceReason.Transitive));
        var totalUnnecessary = results.Sum(r => r.UnnecessaryReferences.Count);

        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine($"- **Projects with issues:** {results.Count}");
        sb.AppendLine($"- **Unused references:** {totalUnused}");
        sb.AppendLine($"- **Transitive references:** {totalTransitive}");
        sb.AppendLine($"- **Total unnecessary references:** {totalUnnecessary}");
        sb.AppendLine();

        if (results.Count == 0)
        {
            sb.AppendLine("✓ No unnecessary references found!");
            return sb.ToString();
        }

        // Details
        sb.AppendLine("## Details");
        sb.AppendLine();

        foreach (var result in results.OrderBy(r => r.ProjectName))
        {
            sb.AppendLine($"### {result.ProjectName}");
            sb.AppendLine();
            sb.AppendLine($"**Project Path:** `{result.ProjectPath}`");
            sb.AppendLine();

            var unusedRefs = result.UnnecessaryReferences
                .Where(u => u.Reason == UnnecessaryReferenceReason.Unused)
                .ToList();

            var transitiveRefs = result.UnnecessaryReferences
                .Where(u => u.Reason == UnnecessaryReferenceReason.Transitive)
                .ToList();

            if (unusedRefs.Any())
            {
                sb.AppendLine("#### Unused References");
                sb.AppendLine();
                sb.AppendLine("The following references are not used in the code:");
                sb.AppendLine();
                foreach (var unusedRef in unusedRefs.OrderBy(u => u.ReferenceName))
                {
                    sb.AppendLine($"- `{unusedRef.ReferenceName}`");
                }

                sb.AppendLine();
            }

            if (transitiveRefs.Any())
            {
                sb.AppendLine("#### Transitive References");
                sb.AppendLine();
                sb.AppendLine("The following references are already accessible through other project references:");
                sb.AppendLine();
                foreach (var transitiveRef in transitiveRefs.OrderBy(u => u.ReferenceName))
                {
                    sb.AppendLine($"- `{transitiveRef.ReferenceName}`");
                    if (!string.IsNullOrEmpty(transitiveRef.TransitivePath))
                    {
                        sb.AppendLine($"  - Path: {transitiveRef.TransitivePath}");
                    }
                }

                sb.AppendLine();
            }
        }

        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("*Generated by Modular Monolith Linter*");

        return sb.ToString();
    }
}